---
name: personalPortfolio
version: 1.00
description: ''
main: index.js
scripts:
  build: webpack -w
  start: node server
  start-dev: webpack -w & nodemon server.js
  test: 'echo "Error: no test specified" && exit 1'
repository:
  type: git
  url: git+https://github.com/showduhtung/PersonalPortfolio.git
keywords: []
author: ''
license: ISC
bugs:
  url: https://github.com/showduhtung/PersonalPortfolio/issues
homepage: https://github.com/showduhtung/PersonalPortfolio#readme
devDependencies:
  '@babel/core': '^7.2.2'
  '@babel/plugin-proposal-class-properties': '^7.3.0'
  '@babel/polyfill': '^7.0.0'
  '@babel/preset-react': '^7.0.0'
  babel-loader: '^8.0.4'
  react-router-dom: '^4.3.1'
  webpack: '^4.27.1'
  webpack-cli: '^3.1.2'
dependencies:
  '@babel/preset-env': '^7.2.0'
  '@material-ui/core': '^3.9.1'
  '@material-ui/icons': '^3.0.2'
  d3: '^4.12.1'
  express: '^4.16.4'
  material-ui-image: '^3.1.0'
  path: '^0.12.7'
  react: '^16.6.3'
  react-dom: '^16.6.3'
  react-icons: '^3.4.0'
  react-scroll: '^1.7.10'
  react-sticky: '^6.0.3'
  roboto-npm-webfont: '^1.0.1'
